services:

  postgres:
    image: postgres:alpine3.22
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    volumes:
      - app-db-data:/var/lib/postgresql/data/pgdata
    env_file:
      - .env
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD?Variable not set}
      - POSTGRES_USER=${POSTGRES_USER?Variable not set}
      - POSTGRES_DB=${POSTGRES_DB?Variable not set}
    ports:
      - 5432:5432

  backend:
    restart: always
    depends_on:
      postgres: 
        condition: service_healthy
        restart: true
    env_file:
      - .env

    build:
      context: ./backend
      dockerfile: Dockerfile

    ports:
      - 8000:8000


  nginx:
    container_name: nginx
    build:
      context: ./web
      dockerfile: Dockerfile

    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      backend:
        condition: service_healthy

volumes:
  app-db-data: {}